"""Add Operation

Revision ID: 9c89e4796087
Revises: 5f334a5074db
Create Date: 2024-01-06 19:31:58.114023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c89e4796087'
down_revision: Union[str, None] = '5f334a5074db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.String(), nullable=False),
        sa.Column('figi', sa.String(), nullable=False),
        sa.Column('instriment_type', sa.String(), nullable=True),
        sa.Column('date', sa.TIMESTAMP(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    # ### end Alembic commands ###
